### ISSUE TITLE
Add CI/CD for Murpheus

### ISSUE THREAD

**Issue by v2thegreat** [Social-Media-Public-Analysis/murpheus#8]
These CI/CD tests should check for:

- [x] Validate tests pass on multiple operating systems (Windows, Unix, and macOS) and versions of Python (currently supported: `3.6`, `3.7`, `3.8`, and `3.9` when released)
- [x] Validate code quality with what we had set up before
- [x] Deployment strategy for PyPi

**Comment by erb13020** [comment]
Working on CD to PyPi

**Comment by erb13020** [comment]
PR #16 #17 both CD to PyPi
